name: Test
on:
  push:
    branches: [ main, tests ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight
  workflow_dispatch:
    branches: [ main, tests ]

jobs:

  build-test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
    # - name: Bootstrap test +MMTk(NoGC)
    #   run: make -C ruby btest RUN_OPTS=--mmtk-plan=NoGC
    - name: Bootstrap test +MMTk(MarkSweep)
      run: make -C ruby btest RUN_OPTS=--mmtk-plan=MarkSweep
    - name: Bootstrap test +MMTk(Immix)
      run: make -C ruby btest RUN_OPTS=--mmtk-plan=Immix
    # - name: MMTk test +MMTk(NoGC)
    #   run: make -C ruby test-all TESTS='test/ruby/test_mmtk.rb' RUN_OPTS="--mmtk-plan=NoGC" TESTOPTS=-v
    - name: MMTk test +MMTk(default plan)
      run: make -C ruby test-all TESTS='test/ruby/test_mmtk.rb' RUN_OPTS="--mmtk" TESTOPTS=-v
    - name: Test +MMTk(MarkSweep)
      run: make -C ruby test-all RUN_OPTS="--mmtk-plan=MarkSweep" TESTOPTS=-v
    - name: Test +MMTk(Immix)
      run: make -C ruby test-all RUN_OPTS="--mmtk-plan=Immix" TESTOPTS=-v
